@startuml scene_widget_lifecycle
title 
Lifecycle of a Scene Widget 
(based on the simpler DisplayLabel Widget - no children)
end title
hide footbox
autonumber
participant React << Framework >>
participant Burrow << WebSocket Server>>
participant DisplayLabel << React Component >>
participant "karabo_hash/decoders" as HashDecoder << module file >>
participant DevicePropertyConnector << singleton >>
participant GuiServerConnector << singleton >>
participant "karabo_hash/builders/monitoring_device" as HashBuilder << module file >>

group Component Mounting
    React -> DisplayLabel: onMount
    note right
    There's no method **onMount** 
    on the component. React 
    calls the first callable 
    provided to React.useEffect()
    end note
    DisplayLabel -> DevicePropertyConnector: registryPropertyMonitor(deviceId, propertyId, onPropertyUpdateCallback)
    DevicePropertyConnector -> HashBuilder : buildStartMonitoringHash(deviceId)
    DevicePropertyConnector -> GuiServerConnector: sendHash(startMonitoringHash) 
    DevicePropertyConnector -> DevicePropertyConnector: devicePropertyMonitors.add(deviceId, propertyId, onPropertyUpdateCallback)
    note right
    devicePropertyMonitors is a map 
    of property to property update 
    handlers internal to the property
    connector singleton. The **add**
    method doesn't exist in the code,
    it's a shortcut used in the diagram
    end note
end

...
|||

group Property Update Processing

Burrow -> GuiServerConnector: onWsMessage(message)
GuiServerConnector -> HashDecoder: blobToHash(wsMessagePayload)
HashDecoder -> GuiServerConnector: deviceConfigsHash
GuiServerConnector -> DevicePropertyConnector: onDeviceConfigurationsCallback(deviceConfigsHash)
note right
onDeviceConfigurationsCallback is a handler 
for device configuration updates that
the DevicePropertyConnector had already set
as part of its initialization by calling
**registerHashHandler("deviceConfigurations")**
on the GuiServerConnector.
end note
DevicePropertyConnector -> DisplayLabel: onPropertyUpdateCallback
DisplayLabel -> DisplayLabel: setLabelValue(updatedValue)
note right
**labelValue** is part of the 
DisplayLabel component state,
so its update triggers a
render-cycle of the label
end note

end

...
|||

group Component Unmounting
    React -> DisplayLabel: onUnmount
    note right
    There's no method **onUnmount**
    on the component. React 
    calls the second callable 
    provided to React.useEffect()
    end note
    DisplayLabel -> DevicePropertyConnector: unregisterPropertyMonitor(deviceId, propertyId, onPropertyUpdateCallback)
    DevicePropertyConnector -> DevicePropertyConnector: devicePropertyMonitors.remove(deviceId, propertyId, onPropertyUpdateCallback)
    note right
    devicePropertyMonitors is a map 
    of property to property update 
    handlers internal to the property
    connector singleton. The **remove**
    method doesn't exist in the code,
    it's a shortcut used in the diagram
    end note
    DevicePropertyConnector -> HashBuilder: buildStopMonitoringHash(deviceId)
    DevicePropertyConnector -> GuiServerConnector: sendHash(stopMonitoringHash)

end

@enduml