@startuml scene_construction_sequence
hide footbox
title Scene Construction Sequence 
autonumber
participant SceneCanvas << React Component >>
participant Scene << Class >>
participant ProjectSceneCache << Singleton >>
participant ProjectDBConnector << Singleton >>
participant LoadedSceneSlice << StateStoreSlice >>
participant React << Framework >>
SceneCanvas -> ProjectSceneCache: getSceneInfoFromQueryParams(queryParams, onProjectSceneInfoCallback)
note right
Upon mounting, the SceneCanvas requests the scene 
referenced by the current URL query parameters
end note
ProjectSceneCache -> ProjectSceneCache: getSceneInfo(domain, project, uuid, onGetSceneInfoCallback)
alt Cache Miss (cache uses LocalStorage)
    ProjectSceneCache -> ProjectDBConnector: getScene(domain, project, uuid, onGetSceneCallback)
    ...
    ProjectDBConnector -> ProjectSceneCache: onGetSceneCallback(getSceneResult)
end
ProjectSceneCache -> ProjectSceneCache: onGetSceneInfoCallback(sceneInfo)
ProjectSceneCache -> SceneCanvas : onProjectSceneInfoCallback(projectSceneInfo)
create Scene
SceneCanvas -> Scene: constructor(projectSceneInfo)
loop 
    Scene -> Scene: buildSceneElements(jsonObjectFromSceneSVG)
    note right
    **buildSceneElements** builds the various
    **SceneElement** instances from the
    JSON object built from the parsing of the 
    scene's SVG. The SceneElement instances aggregate
    references to the React Component that will
    render them on the screen and the properties
    that must be provided for the construction of
    the React Components. The SceneElement instances
    are used on calls to React.createElement at
    the end of the Scene Construction Sequence.
    end note
end
SceneCanvas -> LoadedSceneSlice : setLoadedScene(sceneWidth, sceneHeight) << reducer >>
note right
Dispatch an action about the loaded scene
to the Application State Store
end note
SceneCanvas -> SceneCanvas: setScene
note right
setScene modifies the internal
state of SceneCanvas triggering 
the rendering of the component
end note
SceneCanvas -> SceneCanvas: renderScene()
loop
SceneCanvas -> React: createElement(widget.reactComponent, widget.props)
note right
**SceneElement** is the base class for all
the widgets visible on the scene. Widgets 
that have a corresponding React component 
to render them descend from **WidgetElement**
and those that also display some Karabo
property descend from **DynamicWidgetElement**.
end note
end

@enduml