# run CI only on branches and tags
workflow:
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH

stages:
  - lint
  - test
  - deploy

variables:
  NODE_ENV: test
  PIP_CACHE_DIR: '$CI_PROJECT_DIR/.cache/pip'
  PRE_COMMIT_HOME: '$CI_PROJECT_DIR/.cache/pre-commit'

.default_node_image: &node_image
  image: europeanxfel/karabo-ci:debian-12-node_25.001

.before_script_commands: &before_script_commands
  before_script:
    - corepack enable
    - node -v
    - npm -v
    - yarn -v

# Node/Yarn cache (global)
cache:
  key:
    files:
      - yarn.lock
  policy: pull-push
  paths:
    - .yarn/cache/
    - .yarn/unplugged/
    - .yarn/build-state.yml
    - .yarn/install-state.gz
    - .pnp.cjs
    - .pnp.loader.mjs
    - node_modules/

project-lint:
  stage: lint
  image: python:3.12

  # pip + pre-commit cache (RW)
  cache:
    key: common-ci-cache
    policy: pull-push
    paths:
      - .cache/pip
      - .cache/pre-commit

  script:
    - python -m pip install --upgrade pip
    - python -m pip install --cache-dir "$PIP_CACHE_DIR" pre-commit
    - pre-commit run --all-files

test:
  <<: [*node_image, *before_script_commands]
  stage: test
  script:
    - yarn install --immutable
    - yarn build-staging
    - yarn cov --watchAll=false

prerelease_deploy:
  stage: deploy
  <<: [*node_image, *before_script_commands]
  variables:
    KIWI_BUILD_ARTIFACT_DIR: kiwi/tags/$CI_COMMIT_REF_NAME
  script:
    - yarn install --immutable
    # build-staging bundles the application with the settings from .env.stagging
    - yarn build-staging
    - cd dist
    - tar -czf ../kiwi_$CI_COMMIT_REF_NAME.tar.gz .
    - sshpass -p "$XKIWI_PWD" ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $KIWI_BUILD_UPLOAD_HOST "mkdir -p $KIWI_BUILD_UPLOAD_DIR/$KIWI_BUILD_ARTIFACT_DIR"
    - sshpass -p "$XKIWI_PWD" scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ../kiwi_$CI_COMMIT_REF_NAME.tar.gz $KIWI_BUILD_UPLOAD_HOST:$KIWI_BUILD_UPLOAD_DIR/$KIWI_BUILD_ARTIFACT_DIR
  rules:
    - if: $CI_COMMIT_TAG =~ /^(\d+\.)(\d+\.)(\d+)((a|b|rc|\.)\d+)$/

release_deploy:
  stage: deploy
  <<: [*node_image, *before_script_commands]
  variables:
    KIWI_BUILD_ARTIFACT_DIR: kiwi/tags/$CI_COMMIT_REF_NAME
  script:
    - yarn install --immutable
    # build bundles the application with the settings from .env.production
    - yarn build
    - cd dist
    - tar -czf ../kiwi_$CI_COMMIT_REF_NAME.tar.gz .
    - sshpass -p "$XKIWI_PWD" ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $KIWI_BUILD_UPLOAD_HOST "mkdir -p $KIWI_BUILD_UPLOAD_DIR/$KIWI_BUILD_ARTIFACT_DIR"
    - sshpass -p "$XKIWI_PWD" scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ../kiwi_$CI_COMMIT_REF_NAME.tar.gz $KIWI_BUILD_UPLOAD_HOST:$KIWI_BUILD_UPLOAD_DIR/$KIWI_BUILD_ARTIFACT_DIR
  rules:
    - if: $CI_COMMIT_TAG =~ /^(\d+\.)(\d+\.)(\d+)$/
